n_burnin=       128
n_sample=       4
n_sweep=        8
n_anneal = 256
# final temperature
temperature=    0.001
phi_g=          0
T_hot = 10

seed=0


save_szz=false
# save_sxx=true
# save_syy=true
save_spm=false
save_bb=false

save_state=true

